name: Lint Code Base

#
# Documentación:
# - https://help.github.com/es/articles/workflow-syntax-for-github-actions
# - https://github.com/github/super-linter
#

on:
  push:
    paths-ignore:
    - .vscode/*
    - .editorconfig
    - .gitignore
    - palette.png
    - '**.ejs'
    - site/public/**

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Lint Code Base
      uses: github/super-linter@v2.0.0
